/**
 * Fema API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FMStructureDto2 } from './fMStructureDto2';
import { FMFunctionDto2 } from './fMFunctionDto2';
import { FMFaultDto2 } from './fMFaultDto2';


export interface FMEADto2 { 
    rootFMStructure?: FMStructureDto2;
    fmStructures: Array<FMStructureDto2>;
    fmFunctions: Array<FMFunctionDto2>;
    fmFaults: Array<FMFaultDto2>;
}

