/**
 * Fema API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FMFaultDto2 { 
    code: string;
    longName: string;
    shortName: string;
    riskPriorityFactor: number;
    seq: number;
    fmFunctionCode?: string | null;
    parentFaultCode?: string | null;
    causes: Array<FMFaultDto2>;
}

