/**
 * Fema API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FMFaultDto2 } from './fMFaultDto2';


export interface FMFunctionDto2 { 
    code: string;
    longName: string;
    shortName: string;
    fmStructureCode?: string | null;
    parentFMFunctionCode?: string | null;
    prerequisites: Array<FMFunctionDto2>;
    faultRefs: Array<FMFaultDto2>;
}

