/**
 * Fema API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FMFunctionDto2 } from './fMFunctionDto2';


export interface FMStructureDto2 { 
    code: string;
    longName: string;
    shortName: string;
    category: string;
    parentFMStructureCode: string;
    childFMStructures: Array<FMStructureDto2>;
    seFunctions: Array<FMFunctionDto2>;
}

