/**
 * Fmea API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const FaultType = {
    Fm: 'FM',
    Fe: 'FE',
    Fc: 'FC'
} as const;
export type FaultType = typeof FaultType[keyof typeof FaultType];

