/**
 * Fmea API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FaultType } from './faultType';


export interface FMFaultDto2 { 
    code: string;
    longName: string;
    shortName: string;
    riskPriorityFactor: number;
    seq: number;
    level: number;
    fmFunctionCode?: string | null;
    fmFaultCode?: string | null;
    faultType?: FaultType;
    causes: Array<string>;
}
export namespace FMFaultDto2 {
}


