/**
 * Fmea API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FMFunctionDto2 { 
    code: string;
    longName: string;
    shortName: string;
    seq: number;
    level: number;
    fmStructureCode?: string | null;
    parentFMFunctionCode?: string | null;
    prerequisites: Array<string>;
    faultRefs: Array<string>;
}

