/**
 * Fmea API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FMFunctionDto { 
    code?: string | null;
    longName?: string | null;
    shortName?: string | null;
    level?: number;
    prerequisites?: Array<FMFunctionDto> | null;
}

