/**
 * Fmea API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TreeType = {
    Structure: 'Structure',
    StructureAndFunction: 'StructureAndFunction'
} as const;
export type TreeType = typeof TreeType[keyof typeof TreeType];

