export * from './fMEA.service';
import { FMEAService } from './fMEA.service';
export * from './fMFunctions.service';
import { FMFunctionsService } from './fMFunctions.service';
export * from './fMStructures.service';
import { FMStructuresService } from './fMStructures.service';
export * from './import.service';
import { ImportService } from './import.service';
export * from './products.service';
import { ProductsService } from './products.service';
export const APIS = [FMEAService, FMFunctionsService, FMStructuresService, ImportService, ProductsService];
