// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rongke.Fema.Data;

#nullable disable

namespace rongke.fema.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250526062911_addfmea")]
    partial class addfmea
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Rongke.Fema.Data.FMEA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoreMembersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DesignDepartment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DesignOwner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtendedMembersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FMEAVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PlanDeadline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PlanKickOff")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FMEAs");
                });

            modelBuilder.Entity("Rongke.Fema.Data.FMFault", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FMFunctionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImportCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentFaultId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RiskPriorityFactor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FMFunctionId");

                    b.HasIndex("ParentFaultId");

                    b.ToTable("FMFaults");
                });

            modelBuilder.Entity("Rongke.Fema.Data.FMFunction", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FMStructureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImportCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentFMFunctionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FMStructureId");

                    b.HasIndex("ParentFMFunctionId");

                    b.ToTable("FMFunctions");
                });

            modelBuilder.Entity("Rongke.Fema.Data.FMStructure", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentFMStructureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentFMStructureId");

                    b.ToTable("FMStructures");
                });

            modelBuilder.Entity("Rongke.Fema.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Rongke.Fema.Data.FMFault", b =>
                {
                    b.HasOne("Rongke.Fema.Data.FMFunction", "FMFunctionRef")
                        .WithMany("FaultRefs")
                        .HasForeignKey("FMFunctionId");

                    b.HasOne("Rongke.Fema.Data.FMFault", "ParentFaultRef")
                        .WithMany("Causes")
                        .HasForeignKey("ParentFaultId");

                    b.Navigation("FMFunctionRef");

                    b.Navigation("ParentFaultRef");
                });

            modelBuilder.Entity("Rongke.Fema.Data.FMFunction", b =>
                {
                    b.HasOne("Rongke.Fema.Data.FMStructure", "FMStructureRef")
                        .WithMany("SEFunctions")
                        .HasForeignKey("FMStructureId");

                    b.HasOne("Rongke.Fema.Data.FMFunction", "ParentFMFunctionRef")
                        .WithMany("Prerequisites")
                        .HasForeignKey("ParentFMFunctionId");

                    b.Navigation("FMStructureRef");

                    b.Navigation("ParentFMFunctionRef");
                });

            modelBuilder.Entity("Rongke.Fema.Data.FMStructure", b =>
                {
                    b.HasOne("Rongke.Fema.Data.FMStructure", "ParentFMStructureRef")
                        .WithMany("ChildFMStructures")
                        .HasForeignKey("ParentFMStructureId");

                    b.Navigation("ParentFMStructureRef");
                });

            modelBuilder.Entity("Rongke.Fema.Data.FMFault", b =>
                {
                    b.Navigation("Causes");
                });

            modelBuilder.Entity("Rongke.Fema.Data.FMFunction", b =>
                {
                    b.Navigation("FaultRefs");

                    b.Navigation("Prerequisites");
                });

            modelBuilder.Entity("Rongke.Fema.Data.FMStructure", b =>
                {
                    b.Navigation("ChildFMStructures");

                    b.Navigation("SEFunctions");
                });
#pragma warning restore 612, 618
        }
    }
}
