// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rongke.Fema.Data;

#nullable disable

namespace rongke.fema.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250514134121_add_fema_structure_function_fault")]
    partial class add_fema_structure_function_fault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Rongke.Fema.Data.FMFault", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FMFunctionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentFaultId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RiskPriorityFactor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FMFunctionId");

                    b.HasIndex("ParentFaultId");

                    b.ToTable("FMFaults");
                });

            modelBuilder.Entity("Rongke.Fema.Data.FMFunction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FMStructureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentFMFunctionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FMStructureId");

                    b.HasIndex("ParentFMFunctionId");

                    b.ToTable("FMFunctions");
                });

            modelBuilder.Entity("Rongke.Fema.Data.FMStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentFMStructureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentFMStructureId");

                    b.ToTable("FMStructures");
                });

            modelBuilder.Entity("Rongke.Fema.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Rongke.Fema.Data.FMFault", b =>
                {
                    b.HasOne("Rongke.Fema.Data.FMFunction", "FMFunctionRef")
                        .WithMany("FaultRefs")
                        .HasForeignKey("FMFunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rongke.Fema.Data.FMFault", "ParentFaultRef")
                        .WithMany("Causes")
                        .HasForeignKey("ParentFaultId");

                    b.Navigation("FMFunctionRef");

                    b.Navigation("ParentFaultRef");
                });

            modelBuilder.Entity("Rongke.Fema.Data.FMFunction", b =>
                {
                    b.HasOne("Rongke.Fema.Data.FMStructure", "FMStructureRef")
                        .WithMany("SEFunctions")
                        .HasForeignKey("FMStructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rongke.Fema.Data.FMFunction", "ParentFMFunctionRef")
                        .WithMany("Prerequisites")
                        .HasForeignKey("ParentFMFunctionId");

                    b.Navigation("FMStructureRef");

                    b.Navigation("ParentFMFunctionRef");
                });

            modelBuilder.Entity("Rongke.Fema.Data.FMStructure", b =>
                {
                    b.HasOne("Rongke.Fema.Data.FMStructure", "ParentFMStructureRef")
                        .WithMany("ChildFMStructures")
                        .HasForeignKey("ParentFMStructureId");

                    b.Navigation("ParentFMStructureRef");
                });

            modelBuilder.Entity("Rongke.Fema.Data.FMFault", b =>
                {
                    b.Navigation("Causes");
                });

            modelBuilder.Entity("Rongke.Fema.Data.FMFunction", b =>
                {
                    b.Navigation("FaultRefs");

                    b.Navigation("Prerequisites");
                });

            modelBuilder.Entity("Rongke.Fema.Data.FMStructure", b =>
                {
                    b.Navigation("ChildFMStructures");

                    b.Navigation("SEFunctions");
                });
#pragma warning restore 612, 618
        }
    }
}
